codecov:
  require_ci_to_pass: true

ignore:
  - "*.config.js"
  - "*.config.ts"
  - "*.config.mjs"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/*.config.mjs"
  - "**/scripts/**"
  - "**/dist/**"
  - "**/node_modules/**"
  - "**/bin/**"
  - "**/presets/**"
  - "**/assets/**"

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 5%

flags:
  sdk:
    paths:
      - src/
    carryforward: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
